rename_maps = {
    "af_installs": {
        "Attributed Touch Type": "attributed_touch_type",
        "Attributed Touch Time": "attributed_touch_time",
        "Install Time": "install_time",
        "Media Source": "media_source",
        "Channel": "channel",
        "Keywords": "keywords",
        "Campaign": "campaign",
        "Campaign ID": "campaign_id",
        "Adset": "ad_group",
        "Adset ID": "ad_group_id",
        "Ad": "ad",
        "Ad ID": "ad_id",
        "Ad Type": "ad_type",
        "Site ID": "site_id",
        "Sub Site ID": "sub_site_id",
        "Sub Param 1": "sub_param_1",
        "Sub Param 2": "sub_param_2",
        "Sub Param 3": "sub_param_3",
        "Sub Param 4": "sub_param_4",
        "Sub Param 5": "sub_param_5",
        "Cost Model": "cost_model",
        "Cost Value": "cost_value",
        "Cost Currency": "cost_currency",
        "Region": "region",
        "Country Code": "country_code",
        "State": "state",
        "City": "city",
        "Postal Code": "postal_code",
        "IP": "ip",
        "WIFI": "wifi",
        "Operator": "operator",
        "Carrier": "carrier",
        "Language": "language",
        "AppsFlyer ID": "appsflyer_id",
        "IDFA": "advertising_id",  # дублируется ещё в "idfa"
        "Customer User ID": "customer_user_id",
        "Platform": "platform",
        "Device Type": "device_type",
        "OS Version": "os_version",
        "App Version": "app_version",
        "Attribution Lookback": "attribution_lookback",
        "Google Play Referrer": "gp_referrer",
        "Match Type": "match_type",
        "ATT": "att",
        "Is LAT": "is_lat",
        "Keyword ID": "keyword_id"
    }
}
